# Generated by Django 3.2.5 on 2021-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('others', 'Others'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('fashion', 'Fashion')], max_length=64),
        ),
    ]
