# Generated by Django 3.2.5 on 2021-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210725_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('others', 'Others'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('toys', 'Toys')], max_length=64),
        ),
    ]
