# Generated by Django 3.2.5 on 2021-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('toys', 'Toys'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('others', 'Others')], max_length=64),
        ),
    ]
