# Generated by Django 3.2.5 on 2021-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('toys', 'Toys'), ('fashion', 'Fashion'), ('others', 'Others'), ('electronics', 'Electronics')], max_length=64),
        ),
    ]
