# Generated by Django 3.2.5 on 2021-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210801_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('others', 'Others'), ('toys', 'Toys'), ('fashion', 'Fashion')], max_length=64),
        ),
    ]
