# Generated by Django 3.2.5 on 2021-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('toys', 'Toys'), ('others', 'Others'), ('fashion', 'Fashion')], max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, height_field=450, null=True, upload_to='', width_field=640),
        ),
    ]
