# Generated by Django 3.2.5 on 2021-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210801_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='images/', width_field=250),
        ),
    ]
