# Generated by Django 3.2.5 on 2021-08-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210801_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('others', 'Others'), ('toys', 'Toys'), ('fashion', 'Fashion'), ('electronics', 'Electronics')], max_length=64),
        ),
    ]
