# Generated by Django 3.2.5 on 2021-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('toys', 'Toys'), ('others', 'Others'), ('fashion', 'Fashion')], max_length=64),
        ),
    ]
